set_property SRC_FILE_INFO {cfile:D:/BOLSAIC_eldorado/Codigos/DisplayMaster_RTClkSlave/DisplayMaster_RTClkSlave.srcs/constrs_1/new/Nexys-4-Master.xdc rfile:../../../DisplayMaster_RTClkSlave.srcs/constrs_1/new/Nexys-4-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B13 IOSTANDARD LVCMOS33 PULLUP true} [get_ports {SCL_S}]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS33 PULLUP true} [get_ports {SDA_S}]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D17 IOSTANDARD LVCMOS33 PULLUP true} [get_ports {SCL_M}]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS33 PULLUP true} [get_ports {SDA_M}]
